---
- name: All | Ensure rke2 artifact directory exists
  file:
    path: "{{ rke2_artifact_path_remote }}"
    state: directory
    mode: '0644'

- name: All | Copy artifacts to nodes
  copy:
    src: "{{ rke2_artifact_path_local }}"
    dest: "{{ rke2_artifact_path_remote }}"
    mode: '0644'

- name: All | Copy scripts to nodes
  copy:
    content: "{{ lookup('file', 'scripts/rke2-install.sh') }}"
    dest: "{{ rke2_artifact_path_remote }}/rke2-install.sh"
    mode: '0644'
